version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./shopper_for_python:/application
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: db
    volumes:
      - ./db-8-0-3:/var/lib/mysql
    expose:
      - "3307"
    ports:
      - "3307:3307" #アクセスするポート：コンテナ内のポート
    command: --port 3307
